version: "3.2"
services:

    miespanolteuespanhol:
        image: pereirawe/codetomika:php7.3-apache
        container_name: miespanolteuespanhol-app
        privileged: true
        ports:
            - 8013:80
        volumes:
            - ./:/var/www/html
        networks:
            - internal

networks:
    internal:
        driver: bridge